// lib/daily-facts.ts
// 80 genuine film facts — motivational origin stories, happenstance, and behind-the-scenes
// Daily rotation: different fact per user per day, never repeats until all cycled

export interface CineFact {
  id: number
  category: 'origin' | 'courage' | 'happenstance' | 'history' | 'craft'
  emoji: string
  headline: string
  body: string
}

export const CINE_FACTS: CineFact[] = [
  { id: 1, category: 'courage', emoji: '🥊', headline: 'Rocky was written in 3.5 days', body: 'Sylvester Stallone wrote the Rocky screenplay in 3½ days after watching a Muhammad Ali fight. Studios offered him $300K+ for the script alone — he refused unless he could star in it. They finally agreed to $35K and a small percentage. Rocky went on to win Best Picture.' },
  { id: 2, category: 'origin', emoji: '🃏', headline: "The Joker diary nobody saw", body: "Heath Ledger locked himself in a hotel room for 6 weeks before filming The Dark Knight, filling a diary entirely as the Joker — sketches, clippings, character thoughts. Director Christopher Nolan only discovered the diary after Ledger's passing. Ledger never saw the finished film." },
  { id: 3, category: 'happenstance', emoji: '🦖', headline: 'The T-Rex that moved itself', body: "In Jurassic Park, the T-Rex was never supposed to rampage in the rain. A hydraulic leak in the animatronic caused it to randomly thrash during setup. Spielberg watched it happen, turned to his crew and said 'That's the shot.' It became the film's most iconic scene." },
  { id: 4, category: 'courage', emoji: '🧸', headline: "Toy Story was almost cancelled", body: "Early test screenings of Toy Story described it as 'unwatchable.' Disney nearly shut down the entire production. Pixar begged for 2 more weeks and completely rebuilt Woody's character — from sarcastic bully to loyal friend. The rest became the most beloved animated franchise in history." },
  { id: 5, category: 'origin', emoji: '🎬', headline: 'Nolan started with $6,000', body: "Christopher Nolan made his debut film 'Following' (1998) for $6,000, filming only on weekends with unpaid friends. He had no access to equipment, no studio, no budget. Within 3 years he was directing Memento. Within 10, he had a $200M budget for The Dark Knight." },
  { id: 6, category: 'history', emoji: '⭐', headline: 'Every studio rejected Star Wars', body: "George Lucas pitched Star Wars to every major studio and was rejected. Only 20th Century Fox said yes — but they let him keep the sequel rights thinking them worthless. He also kept the merchandising rights, which studios never cared about back then. Those two decisions made him a billionaire." },
  { id: 7, category: 'origin', emoji: '🎭', headline: "Morgan Freeman's 50-year overnight", body: "Morgan Freeman landed his first major film role in 'Street Smart' at age 50 — earning his first Oscar nomination. He'd been performing since the early 1960s. Nearly 3 decades of small roles, theatre, and persistence. He then won Best Supporting Actor for Million Dollar Baby at 67." },
  { id: 8, category: 'craft', emoji: '🚿', headline: "Psycho's shower scene: 7 days, 0 stabs", body: "The shower scene in Psycho took 7 days to film, used 70 different camera setups, and has 50+ individual edits. Despite being the most famous murder scene in cinema history, Janet Leigh is never actually stabbed on screen. Every cut is designed to make your mind do the work." },
  { id: 9, category: 'happenstance', emoji: '🌟', headline: 'Audrey Hepburn — discovered in a lobby', body: "Audrey Hepburn was spotted in a Monaco hotel lobby by French novelist Colette, who immediately insisted she play the lead in her Broadway adaptation of 'Gigi' — without an audition. Hepburn had no Broadway experience. It launched a career that would earn her EGOT status." },
  { id: 10, category: 'courage', emoji: '🌲', headline: 'Blair Witch: $60K → $248 million', body: "The Blair Witch Project was made for $60,000 — mostly improvised, mostly real fear. The actors were genuinely kept lost in the woods with food withheld to make their distress authentic. It became one of the most profitable films ever made relative to cost, earning $248 million worldwide." },
  { id: 11, category: 'courage', emoji: '💍', headline: 'The ring trilogy nobody wanted', body: "Peter Jackson pitched Lord of the Rings to every Hollywood studio for years and was rejected every time. When New Line Cinema finally agreed, they greenlit all three films simultaneously — an unprecedented gamble. The trilogy grossed $2.9 billion and won 17 Academy Awards." },
  { id: 12, category: 'craft', emoji: '🎻', headline: "Jaws' two notes that changed cinema", body: "John Williams composed the Jaws theme in just two days. When he played it for Spielberg at the piano, Spielberg burst out laughing — he thought Williams was joking. Williams played it again. Spielberg stopped laughing. That two-note motif is now the most recognisable musical warning in film history." },
  { id: 13, category: 'origin', emoji: '👽', headline: "E.T. came from Spielberg's loneliness", body: "E.T. was inspired by an imaginary friend Steven Spielberg invented as a child after his parents' divorce. He's described it as the most personal film he ever made. The alien's face was modeled after poet Carl Sandburg, scientist Albert Einstein, and Ernest Hemingway." },
  { id: 14, category: 'happenstance', emoji: '🐱', headline: "The Godfather's cat was a stray", body: "The iconic image of Marlon Brando holding a cat in The Godfather's opening scene was entirely unplanned. A stray cat wandered onto the set. Brando picked it up mid-scene. The cat purred so loudly during dialogue that some lines had to be re-dubbed — but the image became cinema's most iconic shot." },
  { id: 15, category: 'history', emoji: '🎌', headline: "Parasite — 92 years of precedent broken", body: "Parasite became the first non-English language film to win Best Picture in the Academy Awards' 92-year history. Director Bong Joon-ho's acceptance speech became famous: 'Once you overcome the one-inch-tall barrier of subtitles, you will be introduced to so many more amazing films.'" },
  { id: 16, category: 'craft', emoji: '🔴', headline: "Schindler's List red coat", body: "Schindler's List was filmed almost entirely in black and white. The famous red coat on the little girl was the only colour in the film. Director Steven Spielberg asked his team: 'What if we let one thing be in colour?' It became one of cinema's most powerful and devastating visual choices." },
  { id: 17, category: 'courage', emoji: '⏱️', headline: 'Whiplash: 19 days, 3 Oscars', body: "Whiplash was filmed in just 19 days on a $3.3 million budget. Director Damien Chazelle had been trying to get it made for years; nobody would greenlight it. He finally filmed a 17-minute short as proof of concept. The feature won three Academy Awards and launched one of film's most exciting new voices." },
  { id: 18, category: 'courage', emoji: '🍚', headline: "Ang Lee cooked for 6 years", body: "Before Crouching Tiger, Hidden Dragon, Ang Lee spent 6 consecutive years unemployed in Hollywood after early setbacks — cooking and cleaning for his family while his wife supported them. His wife never once told him to quit. He directed the film that changed action cinema and won 4 Oscars." },
  { id: 19, category: 'courage', emoji: '🦁', headline: "Chadwick Boseman's secret", body: "Chadwick Boseman filmed Black Panther, Avengers: Infinity War, Endgame, and Da 5 Bloods while privately undergoing treatment for stage 3 to stage 4 colon cancer — a diagnosis he kept entirely secret. He never mentioned it publicly. The world only learned of it when he passed in August 2020." },
  { id: 20, category: 'craft', emoji: '🎬', headline: "Mad Max: 17 years in storyboards", body: "Mad Max: Fury Road was in development for 17 years before a single frame was filmed. George Miller used every year of waiting to storyboard every individual shot in the film. The result was a 120-day shoot in Namibia that produced what critics called 'the greatest action film ever made.'" },
  { id: 21, category: 'happenstance', emoji: '🔨', headline: 'Harrison Ford was fixing a door', body: "Harrison Ford was working as a carpenter, installing a door at Francis Ford Coppola's office building, when George Lucas's casting director spotted him in the hallway. He was dragged in to read lines for Star Wars without any preparation. He got the role of Han Solo." },
  { id: 22, category: 'courage', emoji: '📝', headline: "Good Will Hunting in a drawer for 2 years", body: "Matt Damon and Ben Affleck's screenplay for Good Will Hunting sat in a drawer for 2 years. They were told repeatedly they were 'too young' and 'not real writers.' When they finally got it made, they won the Academy Award for Best Original Screenplay at ages 27 and 25." },
  { id: 23, category: 'history', emoji: '👩', headline: "Ripley was written as a man", body: "The original Alien script had all male characters. Director Ridley Scott changed the lead character to a woman at the last minute — without changing a single line of dialogue. Ellen Ripley became cinema's most iconic female protagonist, entirely by a last-minute decision." },
  { id: 24, category: 'happenstance', emoji: '🏆', headline: "2001 got 241 negative reviews — and became the greatest sci-fi film", body: "2001: A Space Odyssey received overwhelmingly negative reviews at its première. Kubrick had 19 minutes cut the day after opening. MGM wanted him to add explanatory narration. Kubrick refused. The film is now routinely ranked the greatest science fiction film ever made." },
  { id: 25, category: 'courage', emoji: '🌙', headline: 'Moonlight: $1.5M, Best Picture', body: "Moonlight became the first LGBTQ+ film and first film with an all-Black cast to win Best Picture. Director Barry Jenkins had spent 3 years getting it funded. Its $1.5M budget made it the lowest-budget Best Picture winner in over 60 years. Jenkins said he thought of every Black kid told their story didn't matter." },
  { id: 26, category: 'history', emoji: '🎭', headline: "Hitchcock was always in his films", body: "Alfred Hitchcock appeared as a cameo in 39 of his own films. His appearances became so anticipated that audiences would search for him from the very start, ruining the suspense. He began placing his cameos early in the first reel specifically so audiences could stop looking and pay attention to the film." },
  { id: 27, category: 'origin', emoji: '🤖', headline: "R2-D2's voice was a person all along", body: "Every sound R2-D2 makes in Star Wars was created by sound designer Ben Burtt using his own voice, processed through a synthesizer. Burtt spent months developing R2's 'language' so it would feel emotional and real despite being entirely electronic. He wanted audiences to understand R2 without subtitles." },
  { id: 28, category: 'courage', emoji: '🎓', headline: "Lupita Nyong'o: debut film, first Oscar", body: "'12 Years a Slave' was Lupita Nyong'o's film debut. Director Steve McQueen discovered her while she was still a student at the Yale School of Drama. She won the Academy Award for Best Supporting Actress for that very first major film role." },
  { id: 29, category: 'craft', emoji: '📅', headline: "Boyhood filmed across 12 real years", body: "Richard Linklater filmed Boyhood over 12 actual years — 2002 to 2013 — using the same actors as they genuinely aged. No studio would finance it. Linklater funded it himself, filming just a few days each year. It received universal critical acclaim and 6 Academy Award nominations." },
  { id: 30, category: 'courage', emoji: '🌍', headline: "Everything Everywhere: 7 Oscars on $14M", body: "Everything Everywhere All at Once was made for $14.3 million by directors who had previously only made music videos and a small indie comedy. It won 7 Academy Awards — the most in a single night in Oscar history — including Best Picture, Director, Actress, and Supporting Actor and Actress." },
  { id: 31, category: 'craft', emoji: '🌀', headline: "Inception's hidden wedding ring clue", body: "In Inception, Cobb wears his wedding ring only when he's in a dream — never in reality. Director Christopher Nolan placed this detail in every single scene as a hidden indicator of which level of reality you're watching. Most viewers only notice it on their second or third viewing." },
  { id: 32, category: 'courage', emoji: '💪', headline: "Michelle Yeoh: 'too old' at 28", body: "Michelle Yeoh was told early in her career that she was 'too old to be an action star' — at 28 years old. She continued working for 30 more years. At 60, she won the Academy Award for Best Actress for Everything Everywhere All at Once — the first Asian actress to win the award." },
  { id: 33, category: 'origin', emoji: '💵', headline: "Jim Carrey's $10M check", body: "In 1990, before he was famous, Jim Carrey wrote himself a cheque for $10,000,000 'for acting services rendered,' post-dated 5 years. He kept it folded in his wallet everywhere he went. He earned $20M for The Mask in 1994. The original cheque was placed in his father's casket." },
  { id: 34, category: 'history', emoji: '👠', headline: "Dorothy's slippers were silver", body: "In L. Frank Baum's original Wizard of Oz novels, Dorothy's magical slippers were silver — not ruby. The filmmakers changed them to red specifically because the new Technicolor process made red shoes photograph so much more dramatically against the yellow brick road." },
  { id: 35, category: 'courage', emoji: '🎤', headline: "Sidney Poitier: denied housing while filming", body: "When Sidney Poitier became the first Black man to win Best Actor at the Academy Awards in 1964, he had been denied housing just years earlier because of racial segregation in the very cities where he was filming. He accepted the Oscar with the words: 'It has been a long journey to this moment.'" },
  { id: 36, category: 'happenstance', emoji: '🌧️', headline: "Blade Runner's rain was a mistake fixed into art", body: "The iconic rain in Blade Runner was added in post-production to cover up an error. Sound designer Terry Rawlings noticed road noise from traffic bleed into the soundtrack. He layered rain over every scene to mask it. The rain became the defining atmosphere of one of cinema's most influential films." },
  { id: 37, category: 'courage', emoji: '🏠', headline: "The room that launched a franchise", body: "'Room' (2015) was filmed entirely in sequence — an almost unheard-of practice in Hollywood — so actors Brie Larson and Jacob Tremblay could authentically live through the emotional journey. Larson won Best Actress. She had been working small roles for over a decade." },
  { id: 38, category: 'courage', emoji: '⛺', headline: "Get Out: 5 years, $4.5M, $255M back", body: "Jordan Peele pitched Get Out to every major studio for 5 years. He was rejected repeatedly. He finally made it for $4.5 million. It earned $255 million worldwide, was nominated for Best Picture, and Peele won Best Original Screenplay — becoming the first Black writer-director nominated for both in the same year." },
  { id: 39, category: 'courage', emoji: '🧹', headline: "Keanu gave away $75 million", body: "Keanu Reeves donated approximately $75 million of his Matrix backend profit points to the special effects and costume design teams — saying they deserved it more than he did. He has repeatedly given up his own salary on productions to ensure other cast and crew could be hired." },
  { id: 40, category: 'courage', emoji: '🌺', headline: "Coco was rewritten 75% after one trip to Mexico", body: "Pixar's Coco initially tested poorly — early audiences struggled to connect with Mexican Día de los Muertos traditions. Rather than simplify the story, Pixar flew the entire crew to Mexico for months of cultural research and rewrote 75% of the film. It won Best Animated Feature and made audiences around the world cry." },
  { id: 41, category: 'origin', emoji: '🐺', headline: "Peter Jackson made a 6-hour Lord of the Rings first", body: "Peter Jackson's initial cut of The Fellowship of the Ring was over 6 hours long. He spent an additional year after principal photography creating the famous extended editions. The theatrical cuts were themselves considered too long by many studio executives — who were proved spectacularly wrong." },
  { id: 42, category: 'craft', emoji: '⏰', headline: "'1917' took 60 days of rehearsal for 20 minutes of screen time", body: "The opening 20-minute 'single take' of 1917 required 60+ days of rehearsal before a single frame was captured. Every department — lighting, props, pyrotechnics, camera — had to be synchronised perfectly. Director Sam Mendes said the rehearsal process was 'unlike anything else in his career.'" },
  { id: 43, category: 'history', emoji: '😂', headline: "Charlie Chaplin lost a Charlie Chaplin contest", body: "Charlie Chaplin once entered a Charlie Chaplin lookalike competition at a San Francisco theatre. He came in third place. He did not win his own lookalike contest." },
  { id: 44, category: 'origin', emoji: '🎸', headline: "Barry Jenkins: 3 years of rejection", body: "Barry Jenkins spent 3 years being turned down for Moonlight funding. During that time, he had no income and nearly left filmmaking entirely. When it was finally made, he dedicated the film to 'every Black kid who has ever been told their story isn't worth telling.'" },
  { id: 45, category: 'craft', emoji: '💻', headline: "The Social Network: written without using Facebook", body: "Aaron Sorkin had never personally visited Facebook's website before writing The Social Network screenplay. He wrote the entire script — about the creation of one of history's most visited websites — in 3 months, based entirely on the book and interviews. It won 3 Academy Awards." },
  { id: 46, category: 'courage', emoji: '🎙️', headline: "Denis Villeneuve learned English to direct", body: "Denis Villeneuve grew up speaking only French in Quebec and taught himself English by watching Hollywood films. He specifically learned English because he wanted to direct English-language cinema. He went on to direct Arrival, Blade Runner 2049, and Dune — three of the most ambitious science fiction films of the era." },
  { id: 47, category: 'happenstance', emoji: '💬', headline: "'I'll be back' was supposed to be different", body: "The famous line 'I'll be back' in The Terminator was written as 'I'll come back.' Arnold Schwarzenegger asked screenwriter James Cameron to change it, arguing that the contraction 'I'll' was too difficult for him to say naturally with his accent. Cameron reluctantly agreed. The change made history." },
  { id: 48, category: 'craft', emoji: '🏝️', headline: "Cast Away filmed on pause for a year", body: "When filming Cast Away, Tom Hanks and the entire crew went home for a full year mid-production so he could lose 50 lbs and grow his beard to the required length for the marooned sequences. Director Robert Zemeckis used the year to film What Lies Beneath. Production resumed seamlessly." },
  { id: 49, category: 'origin', emoji: '🏋️', headline: "Viola Davis: from catching rabbits to the EGOT", body: "Viola Davis grew up in extreme poverty — so severe that she and her siblings caught rabbits for food. She went on to win the Oscar, Emmy, Tony, and Grammy — one of the very few EGOT achievers in performing arts history. She has said: 'I am the result of everyone who came before me. I am the dream of my ancestors.'" },
  { id: 50, category: 'history', emoji: '🦾', headline: "The first CGI character in a major film", body: "The first photorealistic CGI character in a major Hollywood film was the stained-glass knight in Terminator 2: Judgment Day (1991). The same team at Industrial Light & Magic went on to create the dinosaurs in Jurassic Park two years later — completely changing what was possible in film." },
  { id: 51, category: 'courage', emoji: '🎞️', headline: "Ang Lee's quiet decade of films", body: "Between 1991 and 2001, Ang Lee made 6 wildly different films in 4 different languages — all of which defied easy genre categorisation. He was repeatedly told to 'pick a lane.' He refused. He went on to win Best Director twice — for Brokeback Mountain and Life of Pi." },
  { id: 52, category: 'origin', emoji: '🐳', headline: "Moby Dick was a commercial failure", body: "Herman Melville's Moby Dick sold fewer than 3,000 copies in his lifetime and was widely considered a failure. The story of obsession, fate, and the sea was rediscovered decades after his death and is now considered one of the greatest American novels — and has inspired dozens of acclaimed films." },
  { id: 53, category: 'craft', emoji: '🎭', headline: "Meryl Streep: 21 nominations, still working", body: "Meryl Streep has received 21 Academy Award nominations — more than any other performer in the award's history. She received her first nomination at 28, won her most recent at 62, and has never stopped taking challenging, transformative roles across 5 decades of cinema." },
  { id: 54, category: 'happenstance', emoji: '🌙', headline: "Pulp Fiction rebuilt John Travolta's career", body: "By the early 1990s, John Travolta's career was considered finished — he'd had a decade of box office failures. Quentin Tarantino specifically sought him out for Pulp Fiction over studio objections. The film completely revived his career. Tarantino later said: 'I knew exactly what I was doing.'" },
  { id: 55, category: 'courage', emoji: '🎼', headline: "Requiem for a Dream score in 3 days", body: "Composer Clint Mansell wrote the entire score for Requiem for a Dream in just 3 days. He has said the film gave him nightmares throughout and he worked in a frenzied state just to finish. The score — particularly 'Lux Aeterna' — became one of the most used pieces of music in film trailers ever." },
  { id: 56, category: 'history', emoji: '🖥️', headline: "Toy Story required inventing new software", body: "Pixar had to develop entirely new software to render the plaid pattern on Woody's shirt in Toy Story — no existing technology could do it. The team created a program called RenderMan specifically for this challenge. RenderMan has since been used in nearly every major visual effects film ever made." },
  { id: 57, category: 'origin', emoji: '🦁', headline: "The Lion King's lost decade", body: "The Lion King was considered the 'B movie' at Disney during production — it was the backup project while the 'real' film, Pocahontas, got all the best animators and resources. The Lion King went on to gross $968 million and become one of the most beloved animated films in history." },
  { id: 58, category: 'courage', emoji: '🎭', headline: "George Clooney was fired early on", body: "George Clooney was fired from the TV show The Facts of Life early in his career. He spent years doing supporting TV roles and working as a door-to-door insurance salesman and selling women's shoes to pay his rent. ER changed everything when he was 33 — he's now one of Hollywood's most acclaimed actor-directors." },
  { id: 59, category: 'craft', emoji: '🏆', headline: "Judi Dench: 8 minutes, 1 Oscar", body: "Dame Judi Dench has only 8 minutes of screen time in Shakespeare in Love. She won the Academy Award for Best Supporting Actress for those 8 minutes — one of the shortest performances ever to win an acting Oscar." },
  { id: 60, category: 'history', emoji: '🔊', headline: "The first ever recorded film sound effect", body: "The first sound effect ever deliberately recorded for a film was for The Jazz Singer (1927) — a crowd laughing. It was captured accidentally by the sound crew during a test. The director heard it and insisted it be kept. It marked the beginning of the sound era in cinema." },
  { id: 61, category: 'happenstance', emoji: '🌟', headline: "Gal Gadot: $300K to $1 billion franchise", body: "Gal Gadot was cast as Wonder Woman for $300,000 — she had never appeared in a major Hollywood production. The studio was sceptical. The film grossed over $800 million worldwide, spawned a $1 billion+ franchise, and Gadot became one of the highest-paid actresses in Hollywood." },
  { id: 62, category: 'craft', emoji: '🎬', headline: "Stanley Kubrick's meticulous method", body: "Stanley Kubrick was known for shooting scenes dozens to hundreds of times. The iconic 'Here's Johnny!' scene in The Shining required 127 takes. Actress Shelley Duvall has said filming the movie was one of the most physically and emotionally gruelling experiences of her life — and the most memorable." },
  { id: 63, category: 'courage', emoji: '🌏', headline: "Parasite: written in a mountain retreat in 1 week", body: "Bong Joon-ho wrote the Parasite screenplay in a single week during a retreat in the mountains of South Korea. He'd carried the core idea for nearly a decade but couldn't make it work until that isolated week. The film became the first Korean film ever to win the Palme d'Or at Cannes." },
  { id: 64, category: 'origin', emoji: '🎸', headline: "The Star Wars score Fox refused to release", body: "20th Century Fox Records initially refused to release the Star Wars soundtrack, believing nobody would buy a sci-fi orchestral score. They relented and let John Williams release it independently. It became one of the best-selling albums of 1977 and is now the best-selling orchestral film score in history." },
  { id: 65, category: 'courage', emoji: '🧠', headline: "Alfonso Cuarón learned English to direct Harry Potter", body: "Alfonso Cuarón grew up speaking only Spanish in Mexico City and had to learn English specifically to direct Harry Potter and the Prisoner of Azkaban — the first non-British director in the series. He went on to win Best Director Oscars for Gravity and Roma, becoming one of the most decorated directors of his generation." },
  { id: 66, category: 'craft', emoji: '🎭', headline: "Apocalypse Now: 238 days in the jungle", body: "Francis Ford Coppola filmed Apocalypse Now for 238 days in the Philippines jungle — almost 3 times the original schedule. The production was ravaged by typhoons, heart attacks, nervous breakdowns, and Martin Sheen's real-life heart attack on set. The documentary of its making, Hearts of Darkness, is considered almost as compelling as the film itself." },
  { id: 67, category: 'history', emoji: '🏅', headline: "Parasite's translator became famous overnight", body: "Sharon Choi, Bong Joon-ho's personal translator throughout the Parasite awards season, became unexpectedly famous for her simultaneous translation during press conferences. She translated his entire Best Director and Best Picture acceptance speeches at the Oscars in real-time. She later enrolled in film school." },
  { id: 68, category: 'origin', emoji: '🌌', headline: "Gravity was in development for 4 years — nobody thought it was filmable", body: "Alfonso Cuarón developed Gravity for 4 years after every visual effects company told him the opening 17-minute single take was 'technically impossible.' He finally found a team willing to try. They invented entirely new camera systems to film it. The sequence won the Oscar for Visual Effects." },
  { id: 69, category: 'happenstance', emoji: '🎠', headline: "Octavia Spencer: from extra to Oscar", body: "Octavia Spencer was an uncredited stand-in extra in A Time to Kill (1996). 15 years later, she won the Academy Award for Best Supporting Actress for The Help — one of the longest gaps between a background role and an Oscar win in Hollywood history." },
  { id: 70, category: 'history', emoji: '🎬', headline: "Jackie Chan does every stunt himself", body: "Jackie Chan has personally performed every stunt in every film he has made — breaking his nose three times, his orbital bone, his skull, countless fingers, and dislocating his shoulder. Every Jackie Chan film ends with out-take reels of his injuries and failed stunts. He holds the Guinness World Record for most stunts performed by a living actor." },
  { id: 71, category: 'craft', emoji: '🌊', headline: "Dunkirk used real WWII ships", body: "Christopher Nolan used real World War II vessels for Dunkirk — not CGI. He also drenched real actors in freezing cold seawater for months. His philosophy was that actors can only perform genuine distress if they're genuinely uncomfortable. The film was nominated for 8 Academy Awards." },
  { id: 72, category: 'courage', emoji: '💫', headline: "A Beautiful Mind: 8 nominations after bad test screenings", body: "A Beautiful Mind received early test screening descriptions of 'too long' and 'too confusing.' Ron Howard refused to cut it. The film received 8 Academy Award nominations and won Best Picture, Best Director, Best Adapted Screenplay, and Best Supporting Actress." },
  { id: 73, category: 'origin', emoji: '📰', headline: "Citizen Kane was buried for decades", body: "Citizen Kane — now widely considered the greatest film ever made — was so aggressively suppressed by newspaper magnate William Randolph Hearst (the film's subject) that it disappeared from cinemas after its première. It was rediscovered by French critics in the 1950s and reappraised as cinema's masterwork." },
  { id: 74, category: 'happenstance', emoji: '🎭', headline: "Schindler's List and Jurassic Park at the same time", body: "Steven Spielberg directed Schindler's List while simultaneously producing Jurassic Park — both releasing in 1993. He would call editors from the Schindler's List set asking for 'Jurassic Park time' to emotionally recover. He won Best Director for Schindler's List. Both films are in the Library of Congress." },
  { id: 75, category: 'craft', emoji: '🎬', headline: "The Godfather audition that saved a career", body: "During casting for The Godfather, Marlon Brando was explicitly on the studio's 'do not cast' list after years of difficult productions. Director Francis Ford Coppola filmed a secret screen test of Brando in character and showed it to the studio. They watched in silence, then said: 'That's Don Corleone.'" },
  { id: 76, category: 'history', emoji: '🏆', headline: "Tilda Swinton's Oscar is a paperweight", body: "Tilda Swinton keeps her Academy Award for Michael Clayton on the kitchen windowsill of her home in the Scottish Highlands, using it as a paperweight. She has described it as 'the best paperweight I've ever had.'" },
  { id: 77, category: 'origin', emoji: '🚀', headline: "The Matrix: Will Smith's biggest regret", body: "The role of Neo in The Matrix was first offered to Will Smith, who turned it down to make Wild Wild West. He has since said it is one of his biggest career regrets. He later said: 'I watched Keanu and I was like... I don't know if I would have made it as good as Keanu did.'" },
  { id: 78, category: 'courage', emoji: '🌸', headline: "Princess Leia's hair had a history", body: "Princess Leia's iconic double-bun hairstyle was directly inspired by the hairstyles of women fighters in the Mexican Revolution in the early 1900s. George Lucas specifically wanted Leia's look to echo real female revolutionaries. He told Carrie Fisher: 'There are no bras in space.'" },
  { id: 79, category: 'craft', emoji: '🎵', headline: "2001's discarded score cost a fortune", body: "Stanley Kubrick commissioned a full orchestral score from composer Alex North for 2001: A Space Odyssey. He then replaced every note of it with pre-existing classical music — without telling North. North didn't discover his score had been discarded until he attended the film's première. He later sued." },
  { id: 80, category: 'history', emoji: '🌟', headline: "Forrest Gump was turned down 7 times", body: "The role of Forrest Gump was turned down by 7 actors, including John Travolta, Chevy Chase, and Bill Murray. Tom Hanks immediately understood the character in a way others didn't. His preparation included running 1,500 miles across the production — he did every step of it himself." },
]

// ---- Daily fact selection ----

function simpleHash(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0
  }
  return hash
}

const STORAGE_KEY_PREFIX = 'cinescope_facts_'

export interface DailyFactState {
  fact: CineFact
  isNew: boolean // true if not yet shown today
}

export function getDailyFact(userEmail: string): DailyFactState {
  if (typeof window === 'undefined') return { fact: CINE_FACTS[0], isNew: false }

  const today = new Date().toISOString().slice(0, 10) // "2026-03-13"
  const seenKey = `${STORAGE_KEY_PREFIX}seen_${userEmail.replace(/[^a-z0-9]/gi, '_')}`
  const dateKey = `${STORAGE_KEY_PREFIX}date_${userEmail.replace(/[^a-z0-9]/gi, '_')}`

  const lastDate = localStorage.getItem(dateKey) || ''
  const seenRaw = localStorage.getItem(seenKey) || '[]'
  let seenIds: number[] = JSON.parse(seenRaw)

  // Pick a candidate: user+date hash over unseen facts
  const allIds = CINE_FACTS.map(f => f.id)
  const unseenIds = allIds.filter(id => !seenIds.includes(id))

  // If all seen, reset
  const poolIds = unseenIds.length > 0 ? unseenIds : allIds
  if (unseenIds.length === 0) {
    seenIds = []
  }

  const seed = simpleHash(userEmail + today)
  const chosenId = poolIds[seed % poolIds.length]
  const fact = CINE_FACTS.find(f => f.id === chosenId) ?? CINE_FACTS[0]

  const isNew = lastDate !== today

  if (isNew) {
    // Record as shown today
    if (!seenIds.includes(fact.id)) seenIds.push(fact.id)
    localStorage.setItem(seenKey, JSON.stringify(seenIds))
    localStorage.setItem(dateKey, today)
  }

  return { fact, isNew }
}
